### ISSUE TITLE
Limit number of receipts to aggregate

### ISSUE THREAD

**Issue by carlosvdr** [graphprotocol/indexer-rs#143] opened 2024-04-10 20:23 UTC
**Describe the bug**
Since there are too many receipts tap agent errors out with error [413](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413)

`ERROR indexer_tap_agent::tap::sender_account: Error while requesting RAV for sender 0xC3dDf37906724732FfD748057FEBe23379b0710D: Error while requesting RAV for sender 0xC3dDf37906724732FfD748057FEBe23379b0710D and allocation 0x9b83A26cF9866c4832572325bFdbE9C15C383142: Networking or low-level protocol error: Server returned an error status code: 413`

**To Reproduce**
1. I have more than 20k receipts in the db 
2. Create a new query after ssome time the error will appear

**Expected behavior**
For a rav to be created

**Additional context**
This is in reference to this part of the code it was noted before but it can cause issues 
https://github.com/graphprotocol/indexer-rs/blob/e3bebc246801fd931c18b621e8a7046846e54658/tap-agent/src/tap/sender_allocation.rs#L205

**Comment by gusinacio** [comment] 2024-04-11 20:04
maybe duplicate of #96

**Comment by aasseman** [comment] 2024-04-29 21:37
Duplicate of #96

**Closed by aasseman** 2024-04-29 21:37 UTC
Labels: p1
